### PR TITLE
Added Algorithms

### PR DESCRIPTION
**Pull request by ankitvashisht12**
Added Insertion sort, selection sort , randomized quick sort, MCM ( Divide and Conquer) , binary Search and linear Search algorithms

### CODE REVIEW

**Comment by vanshikaarora** [comment]
Hey  I see there is some compilation error in all the files like this https://ide.codingblocks.com/s/142033
can you please check:)

**Comment by ankitvashisht12** [comment]
don't know why online compiler throwing error :thinking:  , working fine on my local machine. Although i have fixed the bug. You can check now. Thanks :)

**Comment by ankitvashisht12** [comment]
Matrix_chain_multiplication is also throwing runtime error in coding blocks online compiler but working fine on geeksforgeeks compiler.You can check here: https://ide.geeksforgeeks.org/NZNLGzqM9F. I think coding blocks compiler is not able to handle some cases

**Comment by vanshikaarora** [comment]
Yeah, I noticed that I have retried the code in geeksforgeeks compiler. Your code is merged, you can contribute more PRs :)

**Comment by ankitvashisht12** [comment]
Thank you, sure i will :smile:

**Pull request merged**
